update action

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -2,8 +2,10 @@ name: Docker Image CI
 
 on:
   push:
-    branches: [ "main" ]
-
+    branches: 
+      - "main"
+    tags: 
+      - "*" # Trigger on all tags
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -25,6 +27,20 @@ jobs:
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+    - name: Determine Docker image tag
+      id: docker_tag
+      run: |
+        if [ "${{ github.event_name }}" == "push" ] && [ -n "${{ github.sha }}" ]; then
+          echo "Image tag will be based on commit hash."
+          echo "::set-output name=tag::$(echo ${{ github.sha }} | cut -c1-6)"
+        elif [ "${{ github.event_name }}" == "push" ] && [ -n "${{ github.ref }}" ]; then
+          echo "Image tag will be based on Git tag."
+          echo "::set-output name=tag::${{ github.ref_name }}"
+        else
+          echo "Unable to determine tag."
+          exit 1
+        fi
 
     - name: Build and push Docker image
       uses: docker/build-push-action@v5
